"""Generate static .pyi stubs so LSPs can autocomplete dynamic model attributes."""

from __future__ import annotations

import keyword
from pathlib import Path
from typing import Any

from aimo.models import AIMOModel, AIMONamespace, aimo

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "aimo" / "__init__.pyi"


def ident(name: str) -> str:
    if not name.isidentifier() or keyword.iskeyword(name):
        return f"_{name}"
    return name


def class_name(path: tuple[str, ...]) -> str:
    parts = []
    for part in path:
        cleaned = "".join(piece.capitalize() for piece in part.split("_") if piece)
        parts.append(cleaned or "Namespace")
    return "_" + "_".join(parts)


def walk(ns: AIMONamespace, path: tuple[str, ...] = ()) -> list[tuple[tuple[str, ...], AIMONamespace]]:
    out = [(path, ns)]
    for name, value in sorted(ns.__dict__.items()):
        if name.startswith("_"):
            continue
        if isinstance(value, AIMONamespace) and not isinstance(value, AIMOModel):
            out.extend(walk(value, path + (name,)))
    return out


def annotation_for(name: str, value: Any, path: tuple[str, ...]) -> str:
    if isinstance(value, AIMOModel):
        return "AIMOModel"
    if isinstance(value, AIMONamespace):
        return class_name(path + (name,))
    return "Any"


def emit_attrs(lines: list[str], ns: AIMONamespace, path: tuple[str, ...]) -> bool:
    public = [(n, v) for n, v in sorted(ns.__dict__.items()) if not n.startswith("_")]
    for name, value in public:
        lines.append(f"    {ident(name)}: {annotation_for(name, value, path)}")
    return bool(public)


def main() -> None:
    aimo.refresh(force=False, quiet=True)
    namespaces = walk(aimo)
    lines: list[str] = [
        "# This file is generated by scripts/generate_stubs.py.",
        "# It exists so static LSPs can autocomplete aimo.openai.gpt_4o-style attributes.",
        "from __future__ import annotations",
        "",
        "from typing import Any, Dict, List, Optional",
        "",
        "class AIMOModel(str):",
        "    raw: Dict[str, Any]",
        "    provider: str",
        "    context: int | None",
        "    context_window: int | None",
        "    input_price: float | None",
        "    output_price: float | None",
        "    input_cost_per_token: float | None",
        "    output_cost_per_token: float | None",
        "    supports_vision: bool",
        "    supports_function_calling: bool",
        "    capabilities: list[str]",
        "    modalities: Any",
        "    release_date: str | None",
        "    provider_id: str | None",
        "    provider_name: str | None",
        "    provider_api: str | None",
        "    provider_logo: str | None",
        "    @property",
        "    def id(self) -> str: ...",
        "    def to_dict(self) -> Dict[str, Any]: ...",
        "    def pretty(self) -> str: ...",
        "",
    ]

    for path, ns in reversed(namespaces):
        if not path:
            continue
        cls = class_name(path)
        lines.append(f"class {cls}:")
        if not emit_attrs(lines, ns, path):
            lines.append("    pass")
        lines.append("")

    lines.append("class AIMORegistry:")
    emit_attrs(lines, aimo, ())
    lines.extend(
        [
            "    def update(self, force: bool = True) -> AIMORegistry: ...",
            "    def refresh(self, *, force: bool = True, quiet: bool = False, allow_network: bool = True) -> AIMORegistry: ...",
            "    def search(self, query: str = \"\", provider: Optional[str] = None, limit: int = 20) -> List[AIMOModel]: ...",
            "    def models(self) -> List[AIMOModel]: ...",
            "    def model_ids(self) -> List[str]: ...",
            "    def to_dict(self) -> Dict[str, Dict[str, Any]]: ...",
            "",
            "aimo: AIMORegistry",
            "__version__: str",
            "__all__: list[str]",
            "",
            "def update(force: bool = True) -> AIMORegistry: ...",
            "def search(query: str = \"\", provider: Optional[str] = None, limit: int = 20) -> List[AIMOModel]: ...",
            "def __getattr__(name: str) -> Any: ...",
            "def __dir__() -> List[str]: ...",
            "",
        ]
    )

    for name, value in [(n, v) for n, v in sorted(aimo.__dict__.items()) if not n.startswith("_")]:
        lines.append(f"{ident(name)}: {annotation_for(name, value, ())}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
